export const QWEATHER_GEO_PROVIDER = Symbol('QWEATHER_GEO_PROVIDER');
export const QWEATHER_AIR_PROVIDER = Symbol('QWEATHER_AIR_PROVIDER');
export const QWEATHER_ALERT_PROVIDER = Symbol('QWEATHER_ALERT_PROVIDER');
export const QWEATHER_FINANCE_PROVIDER = Symbol('QWEATHER_FINANCE_PROVIDER');

