CREATE TABLE "SystemRuntimeConfig" (
  "id" INTEGER NOT NULL,
  "pollingInterval" INTEGER NOT NULL DEFAULT 60000,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "SystemRuntimeConfig_pkey" PRIMARY KEY ("id")
);
